# Schema for the configuration files of the SALESmanago Integration module.

salesmanago_integration.endpoint.*:
  type: config_entity
  label: 'SALESmanago Endpoint'
  mapping:
    id:
      type: string
      label: 'Endpoint id'
    uuid:
      type: string
      label: 'UUID'
    address:
      type: string
      label: 'Endpoint Address'
    client_id:
      type: string
      label: 'Client ID'
    api_secret:
      type: string
      label: 'API Secret'
    langcode:
      type: string
      label: 'Default language'

salesmanago_integration.salesmanago.*:
  type: config_entity
  label: 'SALESmanago Endpoint'
  mapping:
    id:
      type: string
      label: 'SALESmanago entity id'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: string
      label: 'Webform name field ID'
    email:
      type: string
      label: 'Webform email field ID'
    phone:
      type: string
      label: 'Webform phone field ID'
    tags:
      type: array
      label: 'Contact tags'
    message:
      type: string
      label: 'Webform phone field ID'
    forceOptIn:
      type: string
      label: 'Email consent checkbox ID'
    forcePhoneOptIn:
      type: string
      label: 'Phone consent checkbox ID'
    consentCount:
      type: integer
      label: 'Count of custom consents the system will use'
    consentDetails:
      type: mapping
      label: 'Custom consent settings'
      mapping:
        name:
          type: string
          label: 'Consent name'
        field:
          type: string
          label: 'Consent form field ID'
    pickList:
      type: string
      label: 'Picklist field ID'
