# Schema for the configuration files of the SALESmanago Integration module.

salesmanago_integration.endpoint.*:
  type: config_entity
  label: 'SALESmanago Endpoint'
  mapping:
    id:
      type: string
      label: 'Endpoint id'
    uuid:
      type: string
      label: 'UUID'
    address:
      type: string
      label: 'Endpoint Address'
    clientId:
      type: string
      label: 'Client ID'
    apiSecret:
      type: string
      label: 'API Secret'
    langcode:
      type: string
      label: 'Default language'

salesmanago_integration.salesmanago.*:
  type: config_entity
  label: 'SALESmanago request config'
  mapping:
    id:
      type: string
      label: 'SALESmanago entity id'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: string
      label: 'Name field ID'
    email:
      type: string
      label: 'Email field ID'
    phone:
      type: string
      label: 'Phone field ID'
    tags:
      type: array
      label: 'Contact tags'
    forceOptIn:
      type: string
      label: 'Email consent checkbox ID'
    forcePhoneOptIn:
      type: string
      label: 'Phone consent checkbox ID'
    consentDetails:
      type: mapping
      label: 'Custom consent settings'
      mapping:
        name:
          type: string
          label: 'Consent name'
        field:
          type: string
          label: 'Consent form field ID'
    standardDetails:
      type: mapping
      label: 'Standard details settings'
      mapping:
        label:
          type: string
          label: 'Standard detail label'
        field:
          type: string
          label: 'Standard detail field ID'
    notes:
      type: mapping
      label: 'Notes settings'
      mapping:
        label:
          type: string
          label: 'Header to add to note text'
        field:
          type: string
          label: 'Form field for note content'
